// Generated from the bilingual owner-guide research set. Edit content here.
import type { Video } from './types'

export const videos: Video[] = [
  {
    id: "v27-ui-and-settings-example",
    title: "V27 UI and settings example",
    platform: "Douyin",
    url: "https://www.douyin.com/shipin/7635125309495380020",
    language: "Chinese",
    featureTags: ["screen","settings","infotainment"],
    marketShown: "China",
    notes: "Research input only. Do not treat as Egypt equipment proof.",
  },
  {
    id: "vehicle-controls-and-adas-settings-example",
    title: "Vehicle controls and ADAS settings example",
    platform: "Douyin",
    url: "https://www.douyin.com/shipin/7643628507255425076",
    language: "Chinese",
    featureTags: ["vehicle-control","adas"],
    marketShown: "China",
    notes: "Use for menu discovery and label as China-market evidence.",
  },
  {
    id: "automatic-parking-demonstration",
    title: "Automatic parking demonstration",
    platform: "Douyin",
    url: "https://www.douyin.com/shipin/7620287955676088360",
    language: "Chinese",
    featureTags: ["auto-park","parking"],
    marketShown: "China",
    notes: "Needs Egypt Wild/Play confirmation before publishing as available.",
  },
  {
    id: "spare-wheel-removal-demonstration",
    title: "Spare wheel removal demonstration",
    platform: "Douyin",
    url: "https://www.douyin.com/shipin/7618029901685344282",
    language: "Chinese",
    featureTags: ["spare-wheel","tires"],
    marketShown: "China",
    notes: "Observed workflow only. Jack points and torque require official manual.",
  },
  {
    id: "under-hood-cover-access-example",
    title: "Under-hood cover access example",
    platform: "Douyin",
    url: "https://www.douyin.com/shipin/7618050967702865972",
    language: "Chinese",
    featureTags: ["under-hood","maintenance"],
    marketShown: "China",
    notes: "Use only as a visual reference until Egypt documentation is added.",
  },
  {
    id: "v27-comprehensive-review",
    title: "V27 comprehensive review",
    platform: "Bilibili",
    url: "https://www.bilibili.com/video/BV1Ni5C6BEYw/",
    language: "Chinese",
    featureTags: ["review","driving","interior"],
    marketShown: "China",
    notes: "Good for questions to verify later, not final Egypt proof.",
  },
]
